apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-microservice-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Kausha07/kaushal-cloud-microservices.git'
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-prometheus-monitor
  namespace: production
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cloudops-microservice
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
